
CREATE TABLE CREDENTIALS (
                USER_NAME VARCHAR(50) NOT NULL,
                PASSWORD VARCHAR(64) NOT NULL,
                CONSTRAINT CREDENTIALS_pk PRIMARY KEY (USER_NAME)
);


CREATE TABLE ROLES (
                ROLE_ID VARCHAR(30) NOT NULL,
                DESCRIPTION VARCHAR(80) NOT NULL,
                CONSTRAINT ROLES_pk PRIMARY KEY (ROLE_ID)
);


CREATE TABLE USER_ACCOUNT (
                USER_UUID VARCHAR(50) NOT NULL,
                USER_NAME VARCHAR(50) NOT NULL,
                DISPLAY_NAME VARCHAR(50) NOT NULL,
                CONSTRAINT USER_ACCOUNT_pk PRIMARY KEY (USER_UUID)
);


CREATE TABLE USER_ROLES (
                USER_UUID VARCHAR(50) NOT NULL,
                ROLE_ID VARCHAR(30) NOT NULL,
                CONSTRAINT USER_ROLES_pk PRIMARY KEY (USER_UUID, ROLE_ID)
);


ALTER TABLE USER_ACCOUNT ADD CONSTRAINT CREDENTIALS_USER_ACCOUNT_fk
FOREIGN KEY (USER_NAME)
REFERENCES CREDENTIALS (USER_NAME)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE USER_ROLES ADD CONSTRAINT ROLES_USER_ROLES_fk
FOREIGN KEY (ROLE_ID)
REFERENCES ROLES (ROLE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE USER_ROLES ADD CONSTRAINT USER_ACCOUNT_USER_ROLES_fk
FOREIGN KEY (USER_UUID)
REFERENCES USER_ACCOUNT (USER_UUID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
